apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    version: "v1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: akuma88/oldappimage
          ports:
            - name: http
              containerPort: 80
